### ISSUE TITLE
Why doesn't cc-proxy build cc-proxy-config anymore?

### ISSUE THREAD

**Issue by linxiulei** [clearcontainers/packaging#290]
I found no .service file in cc-proxy or cc-proxy-config package, and related configs were deleted from .spec file

**Comment by jodh-intel** [comment]
Originally, there was a single `cc-proxy` running as a host-level system service. However, we changed the architecture so that now there is one proxy instance for every virtual machine instance. This makes the system more flexible and secure.

However, the system-level proxy instance also used to handle KSM settings. Since there are now multiple proxy instances, that no longer makes sense. As such, there is now a new system service called `cc-ksm-throttler` which only handles KSM.

See:

- https://github.com/clearcontainers/runtime/blob/master/docs/architecture/architecture.md#overview

  "*A Clear Containers proxy (cc-proxy) instance is launched for each virtual machine to handle multiplexing and demultiplexing those commands and streams.*"

- https://github.com/kata-containers/ksm-throttler

  This is used to build the `cc-ksm-throttler` binary package using https://github.com/clearcontainers/packaging/tree/master/ksm-throttler/

The changes for the various parts of the system to support "one proxy per VM" are:

- https://github.com/clearcontainers/proxy/pull/167
- https://github.com/clearcontainers/runtime/pull/835
- https://github.com/clearcontainers/runtime/pull/909
- https://github.com/clearcontainers/packaging/issues/199
- https://github.com/clearcontainers/packaging/issues/198

Can you confirm this answers your question so we can close this issue?

**Comment by linxiulei** [comment]
Yes, very clear. Thanks
