### ISSUE TITLE
Wrong configuration.toml with alpha.1

### ISSUE THREAD

**Issue by sameo** [clearcontainers/packaging#9]
After updating my Ubuntu 16.04 machine to alpha.1, I get the following error:

```Shell
$ cc-runtime list
/etc/clear-containers/configuration.toml: Directory does not exist: /usr/var/lib/clear-containers/runtime/bundles/pause_bundle
```
The pause bundle is (rightfully) installed under `/var/lib/clear-containers/runtime/bundles/pause_bundle`

**Comment by jodh-intel** [comment]
Note that currently, to build the runtime for a system using a pre-built hypervisor + artifact packages, you need to do this:

```
$  make QEMUBINDIR=/usr/bin SYSCONFDIR=/etc SHAREDIR=/usr/share PKGLIBEXECDIR=/usr/libexec/clear-containers LOCALSTATEDIR=/var
$ sudo -E PATH=$PATH sh -c "make install QEMUBINDIR=/usr/bin SYSCONFDIR=/etc SHAREDIR=/usr/share PKGLIBEXECDIR=/usr/libexec/clear-containers LOCALSTATEDIR=/var"
```
However, that will be simplified once https://github.com/clearcontainers/runtime/pull/235 lands (today hopefully) since that branch will ensure the config file is generated a build not install time. This allows the full build to become:

```
$  make QEMUBINDIR=/usr/bin SYSCONFDIR=/etc SHAREDIR=/usr/share PKGLIBEXECDIR=/usr/libexec/clear-containers LOCALSTATEDIR=/var
$ sudo -E PATH=$PATH sh -c "make install SYSCONFDIR=/etc"
```

**Comment by jodh-intel** [comment]
https://github.com/clearcontainers/runtime/pull/235 is now merged so we can now use the simpler `make install` ;)

**Comment by jodh-intel** [comment]
Related: https://github.com/clearcontainers/runtime/pull/288
